server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: insurance-management-system
  datasource:
    url: jdbc:h2:mem:insurance-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoint:
    health:
      show-details: always
